Use short-lived access tokens (#36)

diff --git a/develocity-maven.yml b/develocity-maven.yml
--- a/develocity-maven.yml
+++ b/develocity-maven.yml
@@ -3,21 +3,21 @@ spec:
     # Develocity server URL
     url:
       default: 'https://scans.gradle.com'
-    # Maven remote repository to download extension jars from
-    mavenRepo:
-      default: 'https://repo1.maven.org/maven2'
+    # Allow untrusted server
+    allowUntrustedServer:
+      default: 'false'
+    # Short-lived tokens expiry in hours (if not set, default to 2 hours, should be between 1 and 24)
+    shortLivedTokensExpiry:
+      default: ''
     # Develocity Maven extension version
     mavenExtensionVersion:
       default: '1.21.2'
     # Common Custom User Data Maven extension version (see https://github.com/gradle/common-custom-user-data-maven-extension)
     ccudMavenExtensionVersion:
       default: '2.0'
-    # Allow untrusted server
-    allowUntrustedServer:
-      default: 'false'
-    # Enforce URL
-    enforceUrl:
-      default: 'true'
+    # Maven remote repository to download extension jars from
+    mavenRepo:
+      default: 'https://repo1.maven.org/maven2'
     # Capture file fingerprints, only set if no Develocity extension is already present
     captureFileFingerprints:
       default: 'true'
@@ -29,12 +29,16 @@ spec:
     # Expected format 'groupId:artifactId(:version)'
     ccudExtensionCustomCoordinates:
       default: ''
+    # Enforce URL
+    enforceUrl:
+      default: 'true'
 ---
 .injectDevelocityForMaven: |
   ccudMavenExtensionVersion=$[[ inputs.ccudMavenExtensionVersion ]]
   mavenRepo=$[[ inputs.mavenRepo ]]
   mavenExtensionVersion=$[[ inputs.mavenExtensionVersion ]]
   allowUntrustedServer=$[[ inputs.allowUntrustedServer ]]
+  shortLivedTokensExpiry=$[[ inputs.shortLivedTokensExpiry ]]
   enforceUrl=$[[ inputs.enforceUrl ]]
   captureFileFingerprints=$[[ inputs.captureFileFingerprints ]]
   customMavenExtensionCoordinates=$[[ inputs.mavenExtensionCustomCoordinates ]]
@@ -100,7 +104,7 @@ spec:
     then
       mavenOpts="-Dmaven.ext.class.path=${mavenExtClasspath} ${mavenOpts}"
     fi
-    if [[ ("${appliedCustomDv}" = "true" || "${appliedCustomCcud}" = "true") && "${enforceUrl}" = 'true' ]]
+    if [[ ("${appliedCustomDv}" = "true" || "${appliedCustomCcud}" = "true") && "${enforceUrl}" = "true" ]]
     then
       mavenOpts="${mavenOpts} -Dgradle.enterprise.url=${url} -Ddevelocity.url=${url}"
     elif [[ "${appliedCustomDv}" = "false" && "${appliedCustomCcud}" = "false" ]]
@@ -176,9 +180,121 @@ spec:
     local IFS=\>
     read -d \< elementName value
   }
+
+  function createShortLivedToken() {
+    local allKeys="${GRADLE_ENTERPRISE_ACCESS_KEY:-${DEVELOCITY_ACCESS_KEY}}"
+    if [ -z "${allKeys}" ]
+    then
+      return 0
+    fi
+
+    local serverUrl=${1}
+    local expiry="${2}"
+
+    local newAccessKey=""
+    if [[ "${enforceUrl}" == "true" || $(singleKey "${allKeys}") == "true" ]]
+    then
+      local hostname=$(extractHostname "${serverUrl}")
+      local accessKey=$(extractAccessKey "${allKeys}" "${hostname}")
+      local tokenUrl="${serverUrl}/api/auth/token"
+      if [ ! -z "${accessKey}" ]
+      then
+        local token=$(getShortLivedToken $tokenUrl $expiry $accessKey)
+        if [ ! -z "${token}" ]
+        then
+          newAccessKey="${hostname}=${token}"
+        fi
+      else
+        >&2 echo "Could not create short lived access token, no access key matching given Develocity server hostname ${hostname}"
+      fi
+    else
+      local separator=";"
+      IFS="${separator}" read -ra pairs <<< "${allKeys}"
+      for pair in "${pairs[@]}"; do
+        IFS='=' read -r host key <<< "$pair"
+        local tokenUrl="https://${host}/api/auth/token"
+        local token=$(getShortLivedToken $tokenUrl $expiry $key)
+        if [ ! -z "${token}" ]
+        then
+          if [ -z "${newAccessKey}" ]
+          then
+            newAccessKey="${host}=${token}"
+          else
+            newAccessKey="${newAccessKey}${separator}${host}=${token}"
+          fi
+        fi
+      done
+    fi
+
+    export DEVELOCITY_ACCESS_KEY="${newAccessKey}"
+    export GRADLE_ENTERPRISE_ACCESS_KEY="${DEVELOCITY_ACCESS_KEY}"
+  }
+
+  function singleKey() {
+    local allKeys=$1
+    local separator=";"
+    IFS="${separator}" read -ra pairs <<< "${allKeys}"
+    if [ "${#pairs[@]}" -eq 1 ]
+    then
+      echo "true"
+    else
+      echo "false"
+    fi
+  }
+
+  function extractHostname() {
+    local url=$1
+    echo "${url}" | cut -d'/' -f3 | cut -d':' -f1
+  }
+
+  function extractAccessKey() {
+    local allKeys=$1
+    local hostname=$2
+      key="${allKeys#*$hostname=}"    # Remove everything before the host name and '='
+      if [ "${key}" == "${allKeys}" ] # if nothing has changed, it's not a match
+      then
+        echo ""
+      else
+        key="${key%%;*}"              # Remove everything after the first ';'
+        echo "$key"
+      fi
+  }
+
+  function getShortLivedToken() {
+    local tokenUrl=$1
+    local expiry=$2
+    local accessKey=$3
+    local maxRetries=3
+    local retryInterval=1
+    local attempt=0
+
+    if [ ! -z "${expiry}" ]
+    then
+      tokenUrl="${tokenUrl}?expiresInHours=${expiry}"
+    fi
+    while [ ${attempt} -le ${maxRetries} ]
+    do
+      local response=$(curl -s -w "\n%{http_code}" -X POST "${tokenUrl}" -H "Authorization: Bearer ${accessKey}")
+      local status_code=$(tail -n1 <<< "${response}")
+      local shortLivedToken=$(head -n -1 <<< "${response}")
+      if [[ "${status_code}" == "200" && ! -z "${shortLivedToken}" ]]
+      then
+        echo "${shortLivedToken}"
+        return
+      elif [ "${status_code}" == "401" ]
+      then
+        >&2 echo "Develocity short lived token request failed ${serverUrl} with status code 401"
+        return
+      else
+        ((attempt++))
+        sleep ${retryInterval}
+      fi
+    done
+  }
   #functions-end
 
   createTmp
   downloadDvCcudExt
   downloadDvMavenExt
+  createShortLivedToken "${url}" "${shortLivedTokensExpiry}"
   injectDevelocityForMaven "${PWD}"
