Add support for multiple keys (Gradle)

diff --git a/develocity-gradle.yml b/develocity-gradle.yml
--- a/develocity-gradle.yml
+++ b/develocity-gradle.yml
@@ -514,66 +514,108 @@ spec:
       return 0
     fi
 
+    local serverUrl=${1}
+    local expiry="${2}"
+
+    local newAccessKey=""
+    if [[ "${enforceUrl}" == "true" || $(singleKey "${allKeys}") == "true" ]]
+    then
+      local hostname=$(extractHostname "${serverUrl}")
+      local accessKey=$(extractAccessKey "${allKeys}" "${hostname}")
+      local tokenUrl="${serverUrl}/api/auth/token"
+      if [ ! -z "${accessKey}" ]
+      then
+        local token=$(getShortLivedToken $tokenUrl $expiry $accessKey)
+        if [ ! -z "${token}" ]
+        then
+          newAccessKey="${hostname}=${token}"
+        fi
+      else
+        >&2 echo "Could not create short lived access token, no access key matching given Develocity server hostname ${hostname}"
+      fi
+    else
+      local separator=";"
+      IFS="${separator}" read -ra pairs <<< "${allKeys}"
+      for pair in "${pairs[@]}"; do
+        IFS='=' read -r host key <<< "$pair"
+        local tokenUrl="https://${host}/api/auth/token"
+        local token=$(getShortLivedToken $tokenUrl $expiry $key)
+        if [ ! -z "${token}" ]
+        then
+          if [ -z "${newAccessKey}" ]
+          then
+            newAccessKey="${host}=${token}"
+          else
+            newAccessKey="${newAccessKey}${separator}${host}=${token}"
+          fi
+        fi
+      done
+    fi
+
+    export DEVELOCITY_ACCESS_KEY="${newAccessKey}"
+    export GRADLE_ENTERPRISE_ACCESS_KEY="${DEVELOCITY_ACCESS_KEY}"
+  }
+
+  function singleKey() {
+    local allKeys=$1
+    local separator=";"
+    IFS="${separator}" read -ra pairs <<< "${allKeys}"
+    if [ "${#pairs[@]}" -eq 1 ]
+    then
+      echo "true"
+    else
+      echo "false"
+    fi
+  }
+
+  function extractHostname() {
+    local url=$1
+    echo "${url}" | cut -d'/' -f3 | cut -d':' -f1
+  }
+
+  function extractAccessKey() {
+    local allKeys=$1
+    local hostname=$2
+    key="${allKeys#*$hostname=}"    # Remove everything before the host name and '='
+    if [ "${key}" == "${allKeys}" ] # if nothing has changed, it's not a match
+    then
+      echo ""
+    else
+      key="${key%%;*}"              # Remove everything after the first ';'
+      echo "$key"
+    fi
+  }
+
+  function getShortLivedToken() {
+    local tokenUrl=$1
+    local expiry=$2
+    local accessKey=$3
     local maxRetries=3
     local retryInterval=1
     local attempt=0
 
-    local serverUrl=${1}
-    local tokenUrl="${serverUrl}/api/auth/token"
-    local expiry="${2}"
-    local hostname=$(extractHostname "${serverUrl}")
-    local accessKey=$(extractAccessKey "${allKeys}" "${hostname}")
-
-    if [ ! -z "${accessKey}" ]
+    if [ ! -z "${expiry}" ]
     then
-      if [ ! -z "${expiry}" ]
-      then
-        tokenUrl="${tokenUrl}?expiresInHours=${expiry}"
-      fi
-      while [ ${attempt} -le ${maxRetries} ]
-      do
-        local response=$(curl -s -w "\n%{http_code}" -X POST "${tokenUrl}" -H "Authorization: Bearer ${accessKey}")
-        local status_code=$(tail -n1 <<<$response)
-        local shortLivedToken=$(head -n -1 <<<$response)
-        if [[ "${status_code}" == "200" && ! -z "${shortLivedToken}" ]]
-        then
-          export DEVELOCITY_ACCESS_KEY="${hostname}=${shortLivedToken}"
-          export GRADLE_ENTERPRISE_ACCESS_KEY="${DEVELOCITY_ACCESS_KEY}"
-          return
-        elif [ "${status_code}" == "401" ]
-        then
-          >&2 echo "Develocity short lived token request failed ${serverUrl} with status code 401"
-          export DEVELOCITY_ACCESS_KEY=""
-          export GRADLE_ENTERPRISE_ACCESS_KEY=""
-          return
-        else
-          ((attempt++))
-          sleep ${retryInterval}
-        fi
-      done
-    else
-      >&2 echo "Could not create short lived access token, no access key matching given Develocity server hostname ${hostname}"
+      tokenUrl="${tokenUrl}?expiresInHours=${expiry}"
     fi
-    export DEVELOCITY_ACCESS_KEY=""
-    export GRADLE_ENTERPRISE_ACCESS_KEY=""
-  }
-
-  function extractHostname() {
-   local url=$1
-   echo "${url}" | cut -d'/' -f3 | cut -d':' -f1
-  }
-
-  function extractAccessKey() {
-   local allKeys=$1
-   local hostname=$2
-     key="${allKeys#*$hostname=}"    # Remove everything before the host name and '='
-     if [ "${key}" == "${allKeys}" ] # if nothing has changed, it's not a match
-     then
-       echo ""
-     else
-       key="${key%%;*}"              # Remove everything after the first ';'
-       echo "$key"
-     fi
+    while [ ${attempt} -le ${maxRetries} ]
+    do
+      local response=$(curl -s -w "\n%{http_code}" -X POST "${tokenUrl}" -H "Authorization: Bearer ${accessKey}")
+      local status_code=$(tail -n1 <<< "${response}")
+      local shortLivedToken=$(head -n -1 <<< "${response}")
+      if [[ "${status_code}" == "200" && ! -z "${shortLivedToken}" ]]
+      then
+        echo "${shortLivedToken}"
+        return
+      elif [ "${status_code}" == "401" ]
+      then
+        >&2 echo "Develocity short lived token request failed ${serverUrl} with status code 401"
+        return
+      else
+        ((attempt++))
+        sleep ${retryInterval}
+      fi
+    done
   }
 
   function injectDevelocityForGradle() {
