Use short-lived access token

diff --git a/develocity-gradle.yml b/develocity-gradle.yml
--- a/develocity-gradle.yml
+++ b/develocity-gradle.yml
@@ -27,6 +27,9 @@ spec:
     # Allow untrusted server
     allowUntrustedServer:
       default: 'false'
+    # Short-lived tokens expiry in hours (if not set, default to 2 hours, should be between 1 and 24)
+    shortLivedTokensExpiry:
+      default: ''
 
 ---
 .build_scan_links_report:
@@ -35,11 +38,11 @@ spec:
       annotations: $CI_PROJECT_DIR/build-scan-links.json
 
 .injectDevelocityForGradle: |
-  function create_gradle_report_init() {
-    local init_script="${CI_PROJECT_DIR}/build-result-capture.init.groovy"
+  function createGradleReportInit() {
+    local initScript="${CI_PROJECT_DIR}/build-result-capture.init.groovy"
     export BUILD_SCAN_REPORT_PATH="${CI_PROJECT_DIR}/build-scan-links.json"
 
-    cat > $init_script <<'EOF'
+    cat > $initScript <<'EOF'
       import org.gradle.util.GradleVersion
       import java.util.concurrent.atomic.AtomicBoolean
 
@@ -129,10 +132,10 @@ spec:
   EOF
   }
 
-  function create_gradle_init() {
-    local init_script="${CI_PROJECT_DIR}/init-script.gradle"
+  function createGradleInit() {
+    local initScript="${CI_PROJECT_DIR}/init-script.gradle"
 
-    cat > $init_script <<'EOF'
+    cat > $initScript <<'EOF'
       import org.gradle.util.GradleVersion
 
       // note that there is no mechanism to share code between the initscript{} block and the main script, so some logic is duplicated
@@ -501,10 +504,75 @@ spec:
 
   EOF
 
-    export DEVELOCITY_INIT_SCRIPT_PATH="${init_script}"
+    export DEVELOCITY_INIT_SCRIPT_PATH="${initScript}"
   }
 
-  function inject_develocity_for_gradle() {
+  function createShortLivedToken() {
+    local allKeys="${GRADLE_ENTERPRISE_ACCESS_KEY:-${DEVELOCITY_ACCESS_KEY}}"
+    if [ -z "${allKeys}" ]
+    then
+      return 0
+    fi
+
+    local maxRetries=3
+    local retryInterval=1
+    local attempt=0
+
+    local serverUrl=${1}
+    local tokenUrl="${serverUrl}/api/auth/token"
+    local expiry="${2}"
+    local hostname=$(extractHostname "${serverUrl}")
+    local accessKey=$(extractAccessKey "${allKeys}" "${hostname}")
+
+    if [ ! -z "${accessKey}" ]
+    then
+      if [ ! -z "${expiry}" ]
+      then
+        tokenUrl="${tokenUrl}?expiresInHours=${expiry}"
+      fi
+      while [ ${attempt} -le ${maxRetries} ]
+      do
+        local response=$(curl -s -w "\n%{http_code}" -X POST "${tokenUrl}" -H "Authorization: Bearer ${accessKey}")
+        local status_code=$(tail -n1 <<<$response)
+        local shortLivedToken=$(head -n -1 <<<$response)
+        if [[ "${status_code}" == "200" && ! -z "${shortLivedToken}" ]]
+        then
+          export DEVELOCITY_ACCESS_KEY="${hostname}=${shortLivedToken}"
+          export GRADLE_ENTERPRISE_ACCESS_KEY="${DEVELOCITY_ACCESS_KEY}"
+          return
+        elif [ "${status_code}" == "401" ]
+        then
+          >&2 echo "Develocity short lived token request failed ${serverUrl} with status code 401"
+          return
+        else
+          ((attempt++))
+          sleep ${retryInterval}
+        fi
+      done
+    else
+      >&2 echo "Could not create short lived access token, no access key matching given Develocity server hostname ${hostname}"
+    fi
+  }
+
+  function extractHostname() {
+   local url=$1
+   echo "${url}" | cut -d'/' -f3 | cut -d':' -f1
+  }
+
+  function extractAccessKey() {
+   local allKeys=$1
+   local hostname=$2
+     key="${allKeys#*$hostname=}"    # Remove everything before the host name and '='
+     if [ "${key}" == "${allKeys}" ] # if nothing has changed, it's not a match
+     then
+       echo ""
+     else
+       key="${key%%;*}"              # Remove everything after the first ';'
+       echo "$key"
+     fi
+  }
+
+  function injectDevelocityForGradle() {
     export "DEVELOCITY_INJECTION_ENABLED=true"
     export "DEVELOCITY_INJECTION_INIT_SCRIPT_NAME=init-script.gradle"
     export "DEVELOCITY_AUTO_INJECTION_CUSTOM_VALUE=GitLab"
@@ -519,6 +587,7 @@ spec:
     export "GRADLE_PLUGIN_REPOSITORY_PASSWORD=$[[ inputs.gradlePluginRepositoryPassword ]]"
   }
 
-  create_gradle_report_init
-  create_gradle_init
-  inject_develocity_for_gradle
+  createGradleReportInit
+  createGradleInit
+  createShortLivedToken "$[[ inputs.url ]]" "$[[ inputs.shortLivedTokensExpiry ]]"
+  injectDevelocityForGradle
diff --git a/develocity-maven.yml b/develocity-maven.yml
--- a/develocity-maven.yml
+++ b/develocity-maven.yml
@@ -15,6 +15,9 @@ spec:
     # Allow untrusted server
     allowUntrustedServer:
       default: 'false'
+    # Short-lived tokens expiry in hours (if not set, default to 2 hours, should be between 1 and 24)
+    shortLivedTokensExpiry:
+      default: ''
     # Enforce URL
     enforceUrl:
       default: 'true'
@@ -35,6 +38,7 @@ spec:
   mavenRepo=$[[ inputs.mavenRepo ]]
   mavenExtensionVersion=$[[ inputs.mavenExtensionVersion ]]
   allowUntrustedServer=$[[ inputs.allowUntrustedServer ]]
+  shortLivedTokensExpiry=$[[ inputs.shortLivedTokensExpiry ]]
   enforceUrl=$[[ inputs.enforceUrl ]]
   captureFileFingerprints=$[[ inputs.captureFileFingerprints ]]
   customMavenExtensionCoordinates=$[[ inputs.mavenExtensionCustomCoordinates ]]
@@ -176,9 +180,75 @@ spec:
     local IFS=\>
     read -d \< elementName value
   }
+
+  function createShortLivedToken() {
+    local allKeys="${GRADLE_ENTERPRISE_ACCESS_KEY:-${DEVELOCITY_ACCESS_KEY}}"
+    if [ -z "${allKeys}" ]
+    then
+      return 0
+    fi
+
+    local maxRetries=3
+    local retryInterval=1
+    local attempt=0
+
+    local serverUrl=${1}
+    local tokenUrl="${serverUrl}/api/auth/token"
+    local expiry="${2}"
+    local hostname=$(extractHostname "${serverUrl}")
+    local accessKey=$(extractAccessKey "${allKeys}" "${hostname}")
+
+    if [ ! -z "${accessKey}" ]
+    then
+      if [ ! -z "${expiry}" ]
+      then
+        tokenUrl="${tokenUrl}?expiresInHours=${expiry}"
+      fi
+      while [ ${attempt} -le ${maxRetries} ]
+      do
+        local response=$(curl -s -w "\n%{http_code}" -X POST "${tokenUrl}" -H "Authorization: Bearer ${accessKey}")
+        local status_code=$(tail -n1 <<<$response)
+        local shortLivedToken=$(head -n -1 <<<$response)
+        if [[ "${status_code}" == "200" && ! -z "${shortLivedToken}" ]]
+        then
+          export DEVELOCITY_ACCESS_KEY="${hostname}=${shortLivedToken}"
+          export GRADLE_ENTERPRISE_ACCESS_KEY="${DEVELOCITY_ACCESS_KEY}"
+          return
+        elif [ "${status_code}" == "401" ]
+        then
+          >&2 echo "Develocity short lived token request failed ${serverUrl} with status code 401"
+          return
+        else
+          ((attempt++))
+          sleep ${retryInterval}
+        fi
+      done
+    else
+      >&2 echo "Could not create short lived access token, no access key matching given Develocity server hostname ${hostname}"
+    fi
+  }
+
+  function extractHostname() {
+    local url=$1
+    echo "${url}" | cut -d'/' -f3 | cut -d':' -f1
+  }
+
+  function extractAccessKey() {
+    local allKeys=$1
+    local hostname=$2
+      key="${allKeys#*$hostname=}"    # Remove everything before the host name and '='
+      if [ "${key}" == "${allKeys}" ] # if nothing has changed, it's not a match
+      then
+        echo ""
+      else
+        key="${key%%;*}"              # Remove everything after the first ';'
+        echo "$key"
+      fi
+  }
   #functions-end
 
   createTmp
   downloadDvCcudExt
   downloadDvMavenExt
+  createShortLivedToken "${url}" "${shortLivedTokensExpiry}"
   injectDevelocityForMaven "${PWD}"
